spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/bookstore;MODE=LEGACY
      username: sa
      password:
      driver-class-name: org.h2.Driver

  config:
    activate:
      on-profile: local