spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ala24?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 19970417
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  config:
    activate:
      on-profile: operation