spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/bookstore;MODE=LEGACY
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  config:
    activate:
      on-profile: local