spring:
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:tcp://localhost/~/bookstore;MODE=LEGACY
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/ala24?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 19970417
    driver-class-name: com.mysql.cj.jdbc.Driver

  messages:
    basename: messages, errors

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  data:
    web:
      pageable:
        default-page-size: 10

  profiles:
    active: local

server:
  servlet:
    session:
      timeout: 1800

logging.level:
  org.hibernate.SQL: debug