spring:
  messages:
    basename: messages, errors

  data:
    web:
      pageable:
        default-page-size: 10

  profiles:
#    active: operation
    active: local

server:
  servlet:
    session:
      timeout: 1800

logging.level:
  org.hibernate.SQL: debug